namespace Practices.Coding.CSharp.CSharpVersion2;

/*
 * Anonymous types are class types that derive directly from object, and that cannot be cast to any type expect object.
 * 
 * Anonymous types are reference types.
 * 
 * Anonymous types provide a convenient way to encapsulate a set of read-only properties into a single object without
 * having to explicitly define an type first. Type name is generated by the compiler and is not avaialble at the source code level.
 * 
 * 
 */
internal class AnanonymousTypeExample
{
    public void AnanoymousTypes()
    {
        var v = new { Amount = 108, Message = "Hello" };

        Console.WriteLine($"{v.Amount} {v.Message}");

        var products = new List<string>();

        var productQuery = from prod in products
                           select new { Color="Color", Price =0 };

    }
}
